### ISSUE TITLE
Killing enemies

### ISSUE THREAD

**Issue by nad0u** [devilmetal/game_project#3]
if the player is moving toward the enemy like this (arrows indicate the direction):
- player--> enemy-->
- player--> <--enemy

The enemy will be killed instead of the player => the player should die

**Comment by devilmetal** [comment]
Il faut bouger le frame de l'ennmi de 2 au lieu d'1 pixel pendant la phase de check pour les hits.
ça devrait résoudre le problème

**Comment by nad0u** [comment]
bien vu, j'ai changé à 5 pixels car sinon 1 fois sur 2 ça ne marchait pas
