### ISSUE TITLE
Drink a beer

### ISSUE THREAD

**Issue by devilmetal** [devilmetal/game_project#4]
# Issue N°Important
## Goal

Drink a beer and enjoy the life.
## Procedure
- [x] Found a day :calendar: 
- [x] Verify the Banshee's Lodge is open during that day :vertical_traffic_light: 
- [x] Notify everyone :bell: 
- [x]  Order the drinks :money_with_wings: 
- [x]  Drink ! :beers: 
## Coments

Nope !

**Comment by nad0u** [comment]
+1
Je pensais justement à organiser cela prochainement =D
